### PR TITLE
[Stomp] Add stomp protocol support

### PR DESCRIPTION
**Pull request by instabledesign**
|**Q**|**A**|
| ------------- |:-------------:|
| Branch? | master|
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |

I use `https://github.com/stomp-php/stomp-php` to implement the Message publisher/provider

### CODE REVIEW

**Comment by odolbeau** [comment]
Very nice, thanks!

Could you please take a look at incorrect tests?

**Comment by instabledesign** [comment]
i'll do it soon :)

**Comment by instabledesign** [comment]
i fixed the weird test ([#stomp-php/102](https://github.com/stomp-php/stomp-php/pull/102/files))

Due to a bad doc block 
https://github.com/stomp-php/stomp-php/blob/master/src/Client.php#L422

```
 ------ ------------------------------------------------------------------- 
  Line   src/Swarrot/Broker/MessageProvider/SimpleStompMessageProvider.php  
 ------ ------------------------------------------------------------------- 
  74     Calling method getNackFrame() on possibly null value of type       
         Stomp\Protocol\Protocol|null.                                      
 ------ ------------------------------------------------------------------- 
```

Do you have an idea to fix this one?

**Comment by instabledesign** [comment]
i finally fix the phpstan

**Comment by odolbeau** [comment]
Thanks. Is it still WIP or can it be merged?

**Comment by instabledesign** [comment]
it's ok for me :)

**Comment by odolbeau** [comment]
:+1:

**Pull request merged**
