### PR TITLE
Add new relic processor

### PR DESCRIPTION
**Pull request by adrienbrault**
- I do not really know how to unit test the code
- I have not actually tried the code with new relic yet
  - https://discuss.newrelic.com/t/how-can-i-monitor-long-running-php-scripts-properly-rabbitmq-supervisord/3039/11
  - https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-api

### CODE REVIEW

**Comment by ThisIsAreku** [comment]
Waiting for this PR to be merged :+1:

**Comment by odolbeau** [comment]
@adrienbrault Can you rebase your PR to let travis run tests before merging please? :)

**Comment by adrienbrault** [comment]
Rebased

**Comment by rcrowe** [comment]
Any chance this can get merged?

**Comment by odolbeau** [comment]
Merged as well.
Thanks @adrienbrault for this processor.
@rcrowe I'm waiting for your feedback on this processor. ;)

**Pull request merged**
